// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UserId : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208070929550_UserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVZzW7jNhC+F+g7CDoWWMtJ0WA3sHeR2kkRdJ0EUXavAS2NHaIUqZBUGj9bD32kvkKHkvVLybYce7F7s/jzzXD4zXBm/N8//44+vUbMeQGpqOBj92QwdB3ggQgpX47dRC/evXc/ffz5p9FlGL06X/N1p2Yd7uRq7D5pHZ97ngqeICJqENFACiUWehCIyCOh8E6Hw/feydADhHARy3FG9wnXNIL0Az8nggcQ64SwmQiBqfU4zvgpqnNDIlAxCWDs4o9nOcjWuc4FowR18IEteio0/GAUcgtRKOwSldKrh1UMqcCxO1PP1QW45E9Y1QZw6E6KGKRe3cOi3HYduo5X3+o19xY769uM/LF7zfWvp65zkzBG5gwHFoQpcJ347NzXQsIfwEESDeEd0Rok3sl1CKn+azucx2e7meKDNzw1pvAI50ITjRds6d7UFJQiS8h19bVEurjOFX2F8DPwpX4q9J2R13zk9Lcz1/nCKbILN2mZQPV82fdmuVeSAg/Z6k4omunZU4HhGxX4jObRSVicfCoS3NtyTVtgBF8eAgcJCxIKzkyRDw/oVr1oMxFRnGgDcnTafFEgtzO8gXFDXugyhW9Bc517YOmkeqJxFgcG6EeP2eSVFNG9YJlvpWOPvkhkYOwuGhMPRC5B18WPvDIkbAwUqbg9IkVukb6hYjdLfhexwqhqfvX01ZONvrqjdwRyFafHVupvIcODhovdVJgRyo4cpbpIeqGUCGh6R+UD89jC1EseOl1ekim+9ipUM2GaxowGKG/s/mIdvwUq96sKVOacdawTt+ktt3wKDDQ4F4FOk44JUQEJbZvj+cP6CDoYxkW0CmGYWigtCeXa9kbKAxoT1qFxY30P/zU6FejNmSnE+Iahch02f5vYAr1hom0WGXkVutihDvdo3AGyTACe5XRuEcms9UGXfMMUrWRnlUkWcepbzQnb9mbUaWyuqF4Tvn4FKtPNF6Jpvw2uUGiYn8sy/gbyVzavT9bkcP0MLe5dXEGZHHtZdpxn0V5HGj2akTjGyFNJq9cjjp/l1JN3fv/sOcowvEC1JNGFtoUkfIgwZWzMmvQjhCsqlcbkhcyJiYWTMLKWbSFcLqXCO/t2cirli83vbEO1phhYSX/VYld4iMg4b/qw1jlh70oLGMKIbM/0J4IlEd9QM2zEyHPwGko+uDuOnVNXAe3Z3ZHLZLmKWI72QCrz5RpUObw7VpEzV5GKwd1x8hhchemKy8Y5GwSyIrfFT+uRq3N9J0/Igs3ertAWI3fwhfZthzHkJpQszWziZKN9CGKljXWqWNM9sLN8sIaXDX1jylivSnNJIb14XRqvyGgd0bd3bKwQny1xHTTOCw1NePdXSkM0MAsG/jObMIw6ulwwI5wuQOkH8ReY7hO+QPu3fooaRqmQfbf9H2rOv7V661mONPo2/IXI4IlIu0tzmLZMB/7wrV2XBRNEv73psh9Mo+cS4s3otOeytb/SU1C9xk/5sBHhB2lWHIXYzSZDK/NO6sx7Ww9hF273bxHs5zEH7ABkFdO3rNVrVVP/jsNepX5HXnOs+v7HqOntSmxrdd9V3GcPPAbHucAbzWjbVjS3lv2dVX8bans1fYyGQFW1Msvd0gVotg2OU/fbmRiSo/IPG3JS0WUJYf5v4xDUaFGsueYLkbOzoVG+xMoqNMFnkFxITRck0DgdYKKR9jq/EpaYIBfNIbzmt4nGtxCPDNGcrarGMCzfJD9tbtR1Ht3GaeP/EEdANal5yW/57wllYaH3Vcsz2wFh3Gf9opm71OZlW64KpBvBdwRam6/w+geIYoZg6pb75AW6ddtuw7rFRlNKlpJEVQtmI2tNfIKSKyJQQHVHKQ8/ka5h9PrxfyHks11THgAA"; }
        }
    }
}
