// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class EnteredDate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291903572_EnteredDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X227TQBB9R+IfrH0nG4KooHJAJSEogrQVLrxv7HG6Yi/u7rpqvo0HPolfYDaOL7FzbfvAmz2eOTM7l7Pjv7//hB8fpAjuwViu1ZC87vVJACrWCVeLIcld+uod+fjh5YvwcyIfgp+l3sDroaWyQ3LrXHZOqY1vQTLbkzw22urU9WItKUs0HfT77+jrPgWEIIgVBOH3XDkuYfWCryOtYshczsRMJyDsWo5fohVqcMkk2IzFMCT4cGd6hR4JLgRnGEMEIj0xoP57HxCpXKGzzxiUW94sM1g5HJKZvWsqoMpXWG4IUHRtdAbGLb9DWptNExLQTVPatq0sN828/yGZKvdmQILLXAg2FyhImbBAguzsPHLawBdQYJiD5Jo5BwZrMk1gFf86D+fZ2XGpeE/7A58KypTSjjkscCf2dqRgLVtAGWvkDLYLCSb8AZJvoBbutop3xh5KyeDtGQl+KI7dhUbO5NA8X/G+3+/EcFCJWF5ry4s4Twyg/8QAvmF6XJ5UJx/rHG23lOkAjFaL58DBhgUDVc+MsR9ucKxOapuRllnuPMgzt01I63nqThmOvGMcg6lb6s6M561xK3QjcPWI4NDXuMXk9/ycbvVdeakZhRaUUlIP3cE94YxlGTZVg4vWkiAqiGj0KjqdcmSBQWO7hXmqaCtPWDKcs9ZXX7MEJtxYhxVnc+YLPEpkR+1ATksvjdS2ua3OdKnsnwuDJhH3OkzZzNgEDyGRnFbngcr/Fn5d20UxE8xsp8eRFrlUe4h2L0ZJXBsopfB4nC4RNQG7X49HrhmmiVhLT0CqSWYDqhYfj1URTROpEnZxQtoqfbuxaKezWpdlu0v3DXdbpfJeDXlrmMP1YB3eNjqTVqiQABN0zxM/ZdHSOpA9r9CL7sRIYPFdrTBjiqdg3Y3+BX5zQiJ4/NpSka61ifhvdxfuz39wSznxrmvtHOqemfiWme6G8TwrxQ78/lM3hlRo5p6+MDwOprUvJFgZt9oXDu4Gex2ddtN3L6+Dd/6uK78YRjzIXOOZiviKFeGRy0CXF0La/FcJx2D5oobwfy4KYt84NWipM1WpLguAx2lGVKp0etwxLAq7MI6nLHb4Oca2X+22P5nIfQnlHJKpusodVubCWpBzsWyeN6T7/a82ns2Yw6vMv9nnOAKGyX1fXalPORdJFfdkS9vsgPANsu5FjAp3e4RbLCukS62OBFqnbwwZjjjSzg3ITCCYvVIRu4fdsR3O4WbGwjFnC8NkM4OFZB1JxNBzwwU6aFrU/vyvNvX/2h/+AbF9DQOdDwAA"; }
        }
    }
}
