// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TableOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "201209081649006_TableOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
