// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddFriendlyField : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291806055_AddFriendlyField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLTMBC+M8M7eHQnCmHoQMeBKUnDZCBtpy7cFWudapAlV5I7zbNx4JF4BVZx/BM7v5QDN3u9++2n1X5a+ffPX+HHp1QGj2Cs0GpIXvf6JAAVay7UYkhyl7x6Rz5+ePkivOTpU/C99Bt4P4xUdkjuncvOKbXxPaTM9lIRG2114nqxTinjmg76/Xf0dZ8CQhDECoLwNldOpLB6wdeRVjFkLmdypjlIu7bjl2iFGlyxFGzGYhgSfHgwvcKPBBdSMOQQgUxOJNR/7wmRKhUmu0RSbnm3zGCVcEhm9qHpgC5fYLlhQNON0RkYt7yFpA6bchLQzVDajq0iN8N8/iGZKvdmQIKrXEo2l2hImLRAguzsPHLawGdQYJgDfsOcA4N7MuWw4r+uw3l2dlwp3tP+wJeCMqW0Yw43uMO9zRSsZQsouUbOYLuQYCKegH8FtXD3Fd8Zeyotg7dnJPimBHYXBjmTQ3N9xfv+vBMjQHG5vNFWFDxPJNB/JoGvWB6X82rlY51j7JZtOgCj1eJ0nJDWDdptW9SQYwKbot6jBzOet/q38I3A1T2HKqpxCyn1fONvzV1lqSVKC42WWqY7xBzOWJbhLjXEvbYEUaHs0avodA2nBQaN7RYpV2yrTCgdbNzWV0yNTCfCWDdmjs2Zr/yIpx23AzUtszRK2z4s6kqXzv65CGiebL3O0dOs2AQXkaLaV+uBKv+WA2sdF8VMMrP9vBlpmadqz8m1F6M8CTZQSuPxOF1lNwG7X49HriXbRKytJyDVqt2Aqs1drJC2tqzdELTTEa2p0e6ufaJsu1TZK3G2RBiuBXF47HYUUriQAIv0KLhXR7S0DtKed+hFD3IkcdNc7TBjSiRg3Z3+Af4KgQL++/ldDS1rufxvh7jw6z84rk8cHq3hqx6Zie+Z6Y7afzNbd+D3nzs6E6mZe/7kPAbmtMHZnQUHR+iuCVpoZEj4XCPfgl8xcf9ytnblGtLmXTocgxWLGsLfrBXEfj9r0NJnqhJdlheX02RUunRazzGOVbkwTiQsdvg5xm5c3b2+M5mjy2U6Bz5V17nLcndhLaRzuWyuN6T7868uEJucw+vMv9l/sQSkKXAJcK0+5ULyivdkS9vsgPANstYzssK7J8ItlhXSlVZHAq3LN4YMlYenwR2kmUQwe60i9gi7uR2u4WbFwrFgC8PSZgULy5pJxDBzIwUmaEbU+fyvIPX/gh/+ALehj3c9DgAA"; }
        }
    }
}
