// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Users : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208051746161_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVZzW7jNhC+F+g7CDoWWMtJ0WA3sHeR2nERdJ0EUXavAS3RDlGKVEgqjZ9tD32kvkKH+qVEyZYcZ9G9WRTnmx9+wxmN//32z+TTS0SdZywk4WzqnozGroNZwEPCNlM3Uet3791PH3/+aXIZRi/O12Lfqd4HkkxO3Uel4nPPk8EjjpAcRSQQXPK1GgU88lDIvdPx+L13MvYwQLiA5TiTu4QpEuH0AR5nnAU4VgmiSx5iKvN1eOOnqM41irCMUYCnLvx4EqNsn+tcUILABh/T9UCDxh+0QW6pCpRdglFqe7+Ncapw6i7lk7kBtvyJt7UFWLoVPMZCbe/wuhK7Cl3Hq4t6TdlSsi6m9U/dK6Z+PXWd64RStKKwsEZUYteJz859xQX+AzMskMLhLVIKCziTqxCn9udxOI/P+oXigzc+1aHwEGNcIQUHbNnetBRLiTa4sNVXAujiOgvygsPPmG3UY2nvEr0UK6e/nbnOF0aAXSCkRIJN/7Ln3XoXgmAW0u0tlySzc6AB41ca8BnCo5Kw9HzOE5BtOaY9MJxtjoEDhMUCl5yZAx/uIa0G0WbGozhRGuT4tLlGz2STvmoY/kVi4Tp3mKYv5SOJsxweQQ48ZC8Xgkd3nGZ5ka49+DwRgY4Zb7y4R2KDVV39xKvSeWeSp+oOyHItd0iaF3I/QJ5rU/WvgXl2sjPPejH7Fkn5NxfhUTO8X04tEaFvfLF0cfNCSh6Q9GiqmvDQQtBLFjpdyZEZnicTmJlQRWJKAtA3dX+x3G+BKtLJgMpyso514jaT5IbNMcUKOxeBSvuEGZIBCu2Yg/9hLR6G53ayQnugEIE8qMrPk5ivrJjovT5WVeigQagCbQbFikFdVHvbJptFoSFsmF5Tnt9jxuvmHdcM345TLS0s/PJ6CBfnaAjnnjWPo+5DC1PLI6haMy/rzYoezuto4iZLFMeQREZTl684ftbRzd75w3u3KMPwAtnSwpXWlprgKoWGpfFWF78QL4iQCkonWiGd1rMwsrbtIVyhxeCdfToFlYrN+ncmYHa0I6vlNCO2ACciuP1Tf3CdE7ZU2j4jikR7nznjNInYjo51J0bRAdZQisX+OHZHZwLab/sjV62aiVitDkCqurUaVLXcH6vs2EykctHGmXiNo28Sy7OYZd20dZb24nB2TRxM4rbbrQeL28W6Qln0UWYk23uyfShZi9PEyVb7I1Uti4lUrQ4gSdaC1CiSLX1/gtQrg3XT5UWu+zLLN/S4sHQFs2+qWiWzvR/EjIcueqT9SAEywKy8Ovc0q/+9221Ps1TbZ2ZV7OaWkjFl5W5U6EleLffPYqzymW1xHbD9mYS6dPpbqXA00htG/hOdUbjRVbVhiRhZY6nu+V9Yz5Wguh8+1Cm/cKQM6f92skO0/3u/7QZ+tTQmMuwZieARCXv+cpyBSwf++LXzlDXlSL1+nHIYTGOaEsLJqHSasndyMlBR7S4ySLET5geZZ7wJu5tziFb6ndTpd9CYoQ+vh08RDsuWIw4JqiL9XT7nm1+jw4cSwEpIRXAfUahjUgmoZFZncysIC0iMqOmlXYv7Ml37UUI238xxDBehblorr/qq2tF2lLCNeO7zf+DAxP7M3Ts66ZqcZBUebscVh2PNuNs2kWidqXSOVNpQ20cVbzFtMU2rPkT2jFiaM5m3GarYrRiQw/jzDIgpyaaC0H+lMRzUaFHuuWJrXlC0YVGxxWorFII6iC6EImsUKHgdQKeRzkS/Ipromy5a4fCK3SQKiiG4jKMV3ZrB0CzfpT+dHNVtntzE6f8Cx3ABzCS6lN+w3xNCw9LuRUuJ7YDQ6ZNXM32WSle1zbZEuuasJ1AevjLr73EUUwCTN8xHz7jbtv0xrEdsMidoI1BkRjBbyS3xEWg2VIACU6LSB49A1zB6+fgf/zdwfC4eAAA="; }
        }
    }
}
