// <auto-generated />
namespace mesqr.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207291746228_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Xy27bMBC8F+g/CLzHdFw0SAM5QWonhdE4DqI0d1paOUQpUiGpIP62HvpJ/YUuLethyc+kh94sand2uJzhyn9+/fYvXhPhvYA2XMk+Oe50iQcyVBGXsz7JbHx0Si7OP37wr6Lk1Xss4nouDjOl6ZMna9MzSk34BAkznYSHWhkV206oEsoiRXvd7ik97lJACIJYnuffZ9LyBBYP+DhQMoTUZkyMVQTCLNfxTbBA9W5ZAiZlIfQJ/njWnTyOeJeCM+QQgIgPJNT94giRshQWu0JSdv4wT2FRsE/G5rkegCHfYb6ygEt3WqWg7fwe4iptFBGPrqbSZm6ZuZrm6vfJSNpPPeLdZkKwqcCFmAkDxEtPzgKrNHwDCZpZiO6YtaDxTEYRLPgv+3CWnuzXii+023OtoExKZZnFA25xbzIFY9gMCq6B1SgX4l3zV4huQM7sU8l3zF6Lld7nE+L9kBzVhUlWZ1DfX/68ve4NsrNZVBYeqgxz13RpB4ySs8NxfFrpo60alLBlHM+katGzHk4b8sljA7DVkaOIK9xcyR2nu7W1yyqVQ2hukcJKdIOX/DFLUzylmreWK16QG2twFBxuoSTHoKFZ46SSbVkJlYu6abzF0sj0mmtjh8yyKXOdH0RJK2xHT4sqtdY2vVp1ugh2v/OE+sXSaTm/3rFr3ESCZlvsB8r6a+6LZV4QMsH0ersPlMgSueXi2IpRGHEFpVjcH6cyVh2oWj0AqfLWClS13MbyaaOxzWOjrXNrXK1NDWyzTjOkrF5aqGEVfynb3bOppeM8hHjYpBceOQ0Hc2Mh6biATvAsBoLjfquAMZM8BmMf1E9wcxZt9vYhV97sxkTiv5103O1/50w78IpvTCj5wnT4xHR7Hr1vAMVCMfv++bMPzGHjp32j7hxEm+ZQruE+iaYK+eb88rn1xgnVtpNP6x+E/hAMn1UQ7vNQQug+TCrQImYkY1W0F7dTZ1SEtKRhWYRdudSWxyy0+DpEtSy+YB6ZyDDkKplCNJKTzKaZvTQGkqmY1/fr0+31F2N4lbM/Sd2T+RdbQJoctwAT+TXjIip5X6+RzQYIJ5Cl35AVfsEh3GxeIt0quSfQsn1DSEE6tz5AkgoEMxMZsBfYzG13D1c75g85m2mW1DuYryyZBAwr10pggXpGVc/9n6HuD835X1XuZzACDQAA"; }
        }
    }
}
