package com.mesqr.android.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.mesqr.android.db.Table;
import com.mesqr.android.db.Msq;

import com.mesqr.android.db.TableDao;
import com.mesqr.android.db.MsqDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableDaoConfig;
    private final DaoConfig msqDaoConfig;

    private final TableDao tableDao;
    private final MsqDao msqDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableDaoConfig = daoConfigMap.get(TableDao.class).clone();
        tableDaoConfig.initIdentityScope(type);

        msqDaoConfig = daoConfigMap.get(MsqDao.class).clone();
        msqDaoConfig.initIdentityScope(type);

        tableDao = new TableDao(tableDaoConfig, this);
        msqDao = new MsqDao(msqDaoConfig, this);

        registerDao(Table.class, tableDao);
        registerDao(Msq.class, msqDao);
    }
    
    public void clear() {
        tableDaoConfig.getIdentityScope().clear();
        msqDaoConfig.getIdentityScope().clear();
    }

    public TableDao getTableDao() {
        return tableDao;
    }

    public MsqDao getMsqDao() {
        return msqDao;
    }

}
